FROM ortussolutions/boxlang:miniserver
WORKDIR /app
COPY . /app
RUN BOXLANG_INSTALL_HOME=/usr/local/boxlang \
    install-bx-module bx-ai@3.4.0 --local
ENV HOST=0.0.0.0 PORT=80 BOXLANG_HOST=0.0.0.0 BOXLANG_WEBROOT=/app BOXLANG_HEALTH_CHECK=true MAX_MEMORY=1536m MIN_MEMORY=256m
EXPOSE 80
STOPSIGNAL SIGTERM
