#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ZIP="${1:-$ROOT/dist/boxshield-arena.zip}"
LIST="$(mktemp)"; TMP="$(mktemp -d)"
trap 'rm -f "$LIST"; rm -rf "$TMP"' EXIT
unzip -tqq "$ZIP"
unzip -Z1 "$ZIP" >"$LIST"
if grep -E '(^|/)(\.git/|\.ai/|\.env$|\.vercel/|build/|dist/|modules/|boxlang_modules/|testbox/|node_modules/|__pycache__/)|\.(pyc|pyo|log|pid|tmp|bak)$|(^|/)tests/runner\.bx(s)?$' "$LIST"; then echo ZIP-EXCLUSION-FAIL >&2; exit 1; fi
for f in .env.example .gitattributes .github/workflows/ci.yml README.md SECURITY.md sbom.cdx.json Dockerfile.vercel run-tests-mintext.bxs run-mock-pipeline.bxs scripts/http-runtime-gate.sh docs/GITHUB_AND_VERCEL.md docs/assets/boxshield-arena.png; do grep -qx "$f" "$LIST" || { echo "ZIP-MISSING: $f" >&2; exit 1; }; done
unzip -q "$ZIP" -d "$TMP"
python3 "$TMP/scripts/verify_project.py" "$TMP"
"$TMP/scripts/secret-scan.sh"
for f in "$TMP"/scripts/*.sh; do bash -n "$f"; done
if grep -RInE --exclude='verify-zip.sh' '(ChatGPT|Claude|Anthropic|GitHub Copilot|AI-generated|generated by (an )?AI|master[- ]prompt)' "$TMP"; then echo DEVELOPMENT-ASSISTANT-TRACE-FAIL >&2; exit 1; fi
echo ZIP-VERIFICATION-PASS
